[package]
name = "game-client"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }

game-common = { path = "../common" }
bevy = { workspace = true, features = ["2d"] }
bevy_enhanced_input = { workspace = true, features = ["default"] }

wasm-bindgen = "0.2.84"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7" }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Os"]
