[package]
name = "game-client"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
game-common = { path = "../common" }

bevy = { workspace = true, features = [
    "2d",
    "web",
    "webgpu",
    "http",
    "https",
    "audio",
] }
bevy_enhanced_input = { workspace = true, features = ["default"] }
bevy_asset_loader = { workspace = true, features = [
    "2d",
    "progress_tracking",
    "standard_dynamic_assets",
] }
iyes_progress = { workspace = true }
wasm-bindgen = "0.2.84"
console_error_panic_hook = "0.1.7"

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O"]
