[package]
name = "game-common"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
bitflags = { workspace = true }

bevy = { workspace = true, features = ["2d"] }
bevy_enhanced_input = { workspace = true, features = ["default"] }
bevy_common_assets = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = { version = "0.3" }
